import {
  OneToOneOutlined,
  ProfileOutlined,
  ColumnHeightOutlined,
  FileImageOutlined,
} from "@ant-design/icons";

export const componentList = [
  {
    icon: <OneToOneOutlined />,
    title: "容器",
    config: {
      type: "W-Container",
      props: {
        style: {
          display: "flex",
          flexDirection: "column",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          width: "200px",
          height: "200px",
          borderRadius: "0px",
          borderWidth: "0px",
          borderStyle: "solid",
          borderColor: "#D4D4D4",
          marginTop: "0px",
          marginBottom: "0px",
          marginLeft: "0px",
          marginRight: "0px",
          paddingTop: "0px",
          paddingBottom: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          backgroundColor: "#8F4B2E",
        },
        canHref: false,
        hrefUrl: "http://www.baidu.com",
      },
      children: [],
    },
  },
  {
    icon: <ColumnHeightOutlined />,
    title: "分割线",
    config: {
      type: "W-Divider",
      props: {
        orientation: "left",
        content: "text",
        style: {
          width: "100%",
          marginTop: "0px",
          marginBottom: "0px",
          color: "#000",
        },
      },
      children: [],
    },
  },
  {
    icon: <ProfileOutlined />,
    title: "文本",
    config: {
      type: "W-Text",
      props: {
        style: {
          width: "50px",
          display: "block",
          marginTop: "0px",
          marginBottom: "0px",
          marginLeft: "0px",
          marginRight: "0px",
          fontSize: "12px",
          fontWeight: 400,
          color: "#000",
          wordWrap: "break-word",
          wordBreak: "break-all",
        },
        content: "content",
        canHref: false,
        hrefUrl: "http://www.baidu.com",
      },
      children: [],
    },
  },
  {
    icon: <FileImageOutlined />,
    title: "图片",
    config: {
      type: "W-Image",
      props: {
        style: {
          display: "flex",
          flexDirection: "column",
          justifyContent: "flex-start",
          alignItems: "flex-start",
          width: "200px",
          height: "200px",
          borderRadius: "0px",
          borderWidth: "0px",
          borderStyle: "solid",
          borderColor: "#D4D4D4",
          marginTop: "0px",
          marginBottom: "0px",
          marginLeft: "0px",
          marginRight: "0px",
          paddingTop: "0px",
          paddingBottom: "0px",
          paddingLeft: "0px",
          paddingRight: "0px",
          background:
            "url(https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png)",
          backgroundSize: "100%",
        },
        canHref: false,
        hrefUrl: "http://www.baidu.com",
      },
      children: [],
    },
  },
];
