import {
  OneToOneOutlined,
  ProfileOutlined,
  ColumnHeightOutlined,
  FileImageOutlined,
} from "@ant-design/icons";

export const componentList = [
  {
    icon: <OneToOneOutlined />,
    title: '容器',
    config: {
      type: 'W-Container',
      props: {
        style: {
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'flex-start',
          alignItems: 'flex-start',
          width: '10vw',
          height: '20vh',
          borderRadius: '0px',
          borderWidth: '0px',
          borderStyle: 'solid',
          borderColor: '#D4D4D4',
          marginTop: '0vh',
          marginBottom: '0vh',
          marginLeft: '0vw',
          marginRight: '0vw',
          paddingTop: '0vh',
          paddingBottom: '0vh',
          paddingLeft: '0vw',
          paddingRight: '0vw',
          backgroundColor: '#8F4B2E',
        },
        canHref: false,
        hrefUrl: 'http://www.baidu.com',
      },
      children: [],
    },
  },
  {
    icon: <ColumnHeightOutlined />,
    title: '分割线',
    config: {
      type: 'W-Divider',
      props: {
        orientation: 'left',
        content: 'text',
        style: {
          width: '100%',
          marginTop: '0vh',
          marginBottom: '0vh',
          color: '#000',
        },
      },
      children: [],
    },
  },
  {
    icon: <ProfileOutlined />,
    title: '文本',
    config: {
      type: 'W-Text',
      props: {
        style: {
          width: '3vw',
          display: 'block',
          marginTop: '0vh',
          marginBottom: '0vh',
          marginLeft: '0vw',
          marginRight: '0vw',
          fontSize: '12px',
          fontWeight: 400,
          color: '#000',
          wordWrap: 'break-word',
          wordBreak: 'break-all',
        },
        content: 'content',
        canHref: false,
        hrefUrl: 'http://www.baidu.com',
      },
      children: [],
    },
  },
  {
    icon: <FileImageOutlined />,
    title: '图片',
    config: {
      type: 'W-Image',
      props: {
        style: {
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'flex-start',
          alignItems: 'flex-start',
          width: '10vw',
          height: '20vh',
          borderRadius: '0px',
          borderWidth: '0px',
          borderStyle: 'solid',
          borderColor: '#D4D4D4',
          marginTop: '0vh',
          marginBottom: '0vh',
          marginLeft: '0vw',
          marginRight: '0vw',
          paddingTop: '0vh',
          paddingBottom: '0vh',
          paddingLeft: '0vw',
          paddingRight: '0vw',
          background:
            'url(https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png)',
          backgroundSize: '100%',
        },
        canHref: false,
        hrefUrl: 'http://www.baidu.com',
      },
      children: [],
    },
  },
];
